Repository Android-Team-119/Android_Team119_Project, pull requests merged in 2023-09, with the labels that each got.

#3 [FEAT] : ⚙️ 연락처 데이터 클래스 설계
  app/src/main/java/com/example/myapplication/data/Contact.kt
Labels: enhancement

#8 dialog XML 작성 완료
  app/src/main/res/drawable/dialog_profile_img.png
  app/src/main/res/layout/dialog_add_number.xml
Labels: ui

#12 [FEAT] : ⚙️ singleton 활용 ContactManager 클래스 설계
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
Labels: enhancement

#13 [FEAT] : ⚙️ Feat/main 기능 구현
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/testfragment/Test1Fragment.kt
  app/src/main/java/com/example/myapplication/testfragment/Test2Fragment.kt
  app/src/main/java/com/example/myapplication/viewpaperadapter/ViewPagerFragmentAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_test1.xml
  app/src/main/res/layout/fragment_test2.xml
Labels: enhancement

#15 Design/detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/res/layout/activity_contact_detail_fragment.xml
Labels: ui

#16 Feat/contactlist UI
  app/src/main/res/drawable/contactlistfragment_likebutton_image.png
  app/src/main/res/drawable/contactlistfragment_unlikebutton_image.png
  app/src/main/res/layout/cantactlist_item.xml
  app/src/main/res/layout/contactlist_fragment.xml
  app/src/main/res/values/strings.xml
Labels: ui

#23 [FEAT] : ⚙️메인페이지 주석 추가
  app/src/main/java/com/example/myapplication/MainActivity.kt
Labels: enhancement

#24 Design/detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/res/layout/activity_contact_detail_fragment.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/values/strings.xml
Labels: bug

#26 [FIX] : 🐛 ContactManager 주석 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
  app/src/main/res/layout/activity_contact_detail_fragment.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#27 [DESIGN] : 🎨 그리드 타입 UI 설계
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/res/layout/contactlist_item_grid.xml
Labels: ui

#28 Feat/detail
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
Labels: enhancement

#30 Detail Layout 수정
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: ui

#31 [FEAT] : ⚙️유효성 검사 기능
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/res/color/dialog_selector_text_input_color.xml
  app/src/main/res/layout/dialog_add_number.xml
  app/src/main/res/values/dialog_styles.xml
Labels: enhancement

#33 NumberAdd Dialog 사진 등록 기능 구현
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
Labels: enhancement

#34 [FEAT] : ⚙️ 더미데이터 추가 및 fragment 연결
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/viewpaperadapter/ViewPagerFragmentAdapter.kt
  app/src/main/res/drawable/contactlistfragment_sample10_png.png
  app/src/main/res/drawable/contactlistfragment_sample1_png.png
  app/src/main/res/drawable/contactlistfragment_sample2_png.png
  app/src/main/res/drawable/contactlistfragment_sample3_png.png
  app/src/main/res/drawable/contactlistfragment_sample4_png.png
  app/src/main/res/drawable/contactlistfragment_sample5_png.png
  app/src/main/res/drawable/contactlistfragment_sample6_png.png
  app/src/main/res/drawable/contactlistfragment_sample8_png.png
  app/src/main/res/drawable/contactlistfragment_sample9_png.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/cantactlist_item.xml
  app/src/main/res/layout/contactlist_fragment.xml
  app/src/main/res/layout/contactlist_item.xml
Labels: enhancement

#36 Contact 클래스 파일 수정
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/java/com/example/myapplication/data/Contact.kt
Labels: enhancement

#42 [FEAT] : ⚙️ Adapter, DetailFragment 객체 정보 출력
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
Labels: enhancement

#43 [FEAT] : ⚙️ Contact data class 수정
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
Labels: enhancement

#50 [REFACTOR] : ♻️ 메인페이지 뷰페이저2/탭레이아웃 수정
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: refactor

#53 [FIX] : 🐛 리사이클러뷰 수정
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
Labels: bug

#51 Design/layout
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contactlist_item.xml
  app/src/main/res/layout/contactlist_item_grid.xml
  app/src/main/res/layout/dialog_add_number.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ui

#58 Feature/detail
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
Labels: enhancement

#66 [FIX] : 🐛 리사이클러뷰 뷰 리프레시가 안되던 버그 수정
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactGridFragment.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
Labels: bug

#67 [REFACTOR] : ♻️ 주석 작성
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
Labels: documentation

#68 [REFACTOR] : ♻️ 유효성 검사 복구
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
Labels: refactor

#69 0905 Main update
  README.md
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/ContactGridFragment.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/data/Contact.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
  app/src/main/java/com/example/myapplication/viewpaperadapter/ViewPagerFragmentAdapter.kt
  app/src/main/res/drawable/main_additem_icon.xml
  app/src/main/res/drawable/main_uparrow_icon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contactlist_fragment.xml
  app/src/main/res/layout/contactlist_item.xml
  app/src/main/res/layout/contactlist_item_grid.xml
  app/src/main/res/layout/dialog_add_number.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_contact_grid.xml
  app/src/main/res/menu/main_item_toolbarmenu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: backup

#71 [FEAT] : ⚙️ 통화버튼을 누르면 전화번호 전달
  app/build.gradle
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
Labels: enhancement

#77 [FIX] :🐛 Dialog에서 값 전송시 Adapter에 생긴 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/AddNumberDialog.kt
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/testfragment/Test1Fragment.kt
  app/src/main/java/com/example/myapplication/testfragment/Test2Fragment.kt
  app/src/main/res/drawable/contactdetailfragment_phonecall.png
  app/src/main/res/layout/fragment_test1.xml
  app/src/main/res/layout/fragment_test2.xml
Labels: bug

#80 [FEAT] : ⚙️ 플로팅 버튼 기능 구현
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contactlist_fragment.xml
Labels: enhancement

#82 [FIX] : 🐛 삭제 버그 해결, Contact_detail 버튼이름 수정
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: bug

#84 Feature/uri
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
  app/src/main/java/com/example/myapplication/testActivity/TestUrlActivity.kt
  app/src/main/res/layout/activity_test_url.xml
Labels: enhancement

#89 [REFACTOR] : ♻️string.xml 수정
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
  app/src/main/java/com/example/myapplication/testActivity/TestUrlActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_test_url.xml
  app/src/main/res/layout/contactlist_fragment.xml
  app/src/main/res/layout/contactlist_item.xml
  app/src/main/res/layout/contactlist_item_grid.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#93 Feature/add number
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/DataUpdateListener.kt
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/UpdateNumberDialog.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
  app/src/main/java/com/example/myapplication/viewpaperadapter/ViewPagerFragmentAdapter.kt
Labels: bug, enhancement

#94 [FIX] : 🐛 Drawable to Uri 기능
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/data/Contact.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
  app/src/main/res/layout/contactlist_item.xml
Labels: bug, enhancement

#96 [FIX] : 🐛 GridView보기 상태에서 수정 시 리사이클러뷰 notify가 안되는 내용 수정
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/MainActivity.kt
Labels: bug

#99 [FEAT] : ⚙️ 메시지 버튼 누르면 메시지앱으로 연결
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#103 [FIX] : 🐛 마이페이지 수정 기능 수정
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/UpdateNumberDialog.kt
  app/src/main/java/com/example/myapplication/data/ContactManager.kt
  app/src/main/res/values-night/themes.xml
Labels: bug

#104 [FIX] : 🐛 마이페이지 수정 이미지 즉시 반영
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
Labels: bug

#110 [FIX] : 🐛 잡다한 버그 수정(issue참고)
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/UpdateNumberDialog.kt
Labels: bug

#112 1차 최종본 Main backup
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/IntroActivity.kt
  app/src/main/java/com/example/myapplication/UpdateNumberDialog.kt
  app/src/main/res/drawable/introactivity_image_png.png
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/values/strings.xml
Labels: backup

#114 [FIX] : 🐛 연락처 불러오기 실행시 contact속 img 가 null 값일때 profile이미지 보이게 수정
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
Labels: bug

#116 [FEAT] : ⚙️휴대폰에 있는 연락처 추가 후 RecyclerView 에 데이터가 추가되었는지 바로 확인할 수 있게 수정
  app/src/main/java/com/example/myapplication/ContactAdapter.kt
  app/src/main/java/com/example/myapplication/ContactDetailFragment.kt
  app/src/main/java/com/example/myapplication/ContactListFragment.kt
  app/src/main/java/com/example/myapplication/MainActivity.kt
Labels: enhancement
